version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: bitnami

  producer:
    image: event-poc-app:latest
    container_name: event-producer
    #depends_on:
    #  - rabbitmq
    #  - tts
    #  - renderer
    #  - coordinator
    restart: on-failure
    environment:
      ROLE: producer
      RABBIT_HOST: rabbitmq
    volumes:
      - ./artifacts:/artifacts
    entrypoint: []

  tts:
    image: event-poc-app:latest
    container_name: event-tts
    depends_on:
      - rabbitmq
    environment:
      ROLE: tts
      RABBIT_HOST: rabbitmq
    volumes:
      - ./artifacts:/artifacts

  renderer:
    image: event-poc-app:latest
    container_name: event-renderer
    depends_on:
      - rabbitmq
    environment:
      ROLE: renderer
      RABBIT_HOST: rabbitmq
    volumes:
      - ./artifacts:/artifacts

  coordinator:
    image: event-poc-app:latest
    container_name: event-coordinator
    depends_on:
      - rabbitmq
    environment:
      ROLE: coordinator
      RABBIT_HOST: rabbitmq
    volumes:
      - ./artifacts:/artifacts
