apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ppt-upload-pvc
  namespace: event-poc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
