apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbit
  namespace: default
spec:
  replicas: 2
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
  persistence:
    storageClassName: efs-sc
    storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-mgmt-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing 
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-rabbit
                port:
                  number: 15672    
