name: pptx_downloader_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - pip
  - pip:
      - python-pptx
      - pillow
      - pdf2image
      - PyMuPDF
      - fastapi==0.109.0
      - uvicorn[standard]==0.24.0
      - pika==1.3.2
      - aio-pika==8.2.4
      - python-multipart==0.0.20
      - celery==5.5.1
      - boto3==1.39.8
