apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-artifacts
  namespace: event-poc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv
  resources:
    requests:
      storage: 5Gi
