apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b27ad96a3b55dd63   # <-- your EFS file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-artifacts
  namespace: event-poc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: efs-pv
  resources:
    requests:
      storage: 5Gi
