apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-speech-vars
  namespace: event-poc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: azure-speech-secret
    creationPolicy: Owner
  data:
    - secretKey: SPEECH_KEY
      remoteRef:
        key: dev/event_poc/azure_speech_vars
        property: SPEECH_KEY
    - secretKey: SPEECH_REGION
      remoteRef:
        key: dev/event_poc/azure_speech_vars
        property: SPEECH_REGION

