apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppt-extractor-service
  namespace: event-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppt-extractor
  template:
    metadata:
      labels:
        app: ppt-extractor
    spec:
      containers:
      - name: ppt-extractor
        image: 228122752878.dkr.ecr.us-east-1.amazonaws.com/event-driven-poc-ppt-extractor
        command: ["/bin/bash", "-c"]
        args:
          - |
            source /opt/conda/etc/profile.d/conda.sh && \
            conda activate pptx_extractor_env && \
            echo "Starting celery..." && \
            celery -A tasks worker --loglevel=info -Q ppt_tasks
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-artifacts
          mountPath: /artifacts
        env:
        - name: RABBITMQ_HOST
          value: "my-rabbit-nodes.default.svc.cluster.local"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: username
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: password      
      volumes:
      - name: shared-artifacts
        persistentVolumeClaim:
          claimName: shared-artifacts
