apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-processor-service
  namespace: event-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-processor
  template:
    metadata:
      labels:
        app: tts-processor
    spec:
      containers:
      - name: tts-processor
        image: 228122752878.dkr.ecr.us-east-1.amazonaws.com/event-driven-poc-tts-processor
        command: ["/bin/bash", "-c"]
        args:
          - |
            source /opt/conda/etc/profile.d/conda.sh && \
            conda activate tts_processor_env && \
            echo "Starting celery..." && \
            celery -A tts_processor worker --loglevel=info -Q tts_tasks
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-artifacts
          mountPath: /artifacts
        env:
        - name: SPEECH_KEY
          valueFrom:
            secretKeyRef:
              name: azure-speech-secret
              key: SPEECH_KEY
        - name: SPEECH_REGION
          valueFrom:
            secretKeyRef:
              name: azure-speech-secret
              key: SPEECH_REGION
        - name: PIPER_BINARY
          value: "/root/.local/share/piper/piper"
        - name: RABBITMQ_HOST
          value: "my-rabbit-nodes.default.svc.cluster.local"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: username
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: password      
      volumes:
      - name: shared-artifacts
        persistentVolumeClaim:
          claimName: shared-artifacts
