apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-producer-service
  namespace: event-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-producer
  template:
    metadata:
      labels:
        app: video-producer
    spec:
      containers:
      - name: video-producer
        image: 228122752878.dkr.ecr.us-east-1.amazonaws.com/event-driven-poc-video-producer
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-artifacts
          mountPath: /artifacts
        env:
        - name: RABBITMQ_HOST
          value: "my-rabbit-nodes.default.svc.cluster.local"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: username
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-rabbit-default-user
              key: password
        - name: RES_WIDTH
          value: "1920"
        - name: RES_HEIGHT
          value: "1080" 
        - name: FPS
          value: "30"
      volumes:
      - name: shared-artifacts
        persistentVolumeClaim:
          claimName: shared-artifacts
