auth:
  username: user
  password: bitnami
  erlangCookie: secretcookie

service:
  type: ClusterIP

persistence:
  enabled: false

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 250m
