apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: event-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: 228122752878.dkr.ecr.us-east-1.amazonaws.com/event-driven-poc-app:latest
        env:
        - name: ROLE
          value: "coordinator"
        volumeMounts:
        - name: shared-artifacts
          mountPath: /artifacts
      volumes:
      - name: shared-artifacts
        persistentVolumeClaim:
          claimName: shared-artifacts
