apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbit
  namespace: default
spec:
  replicas: 2
  service:
    type: LoadBalancer
  persistence:
    storageClassName: efs-sc
    storage: 5Gi
