AWSTemplateFormatVersion: '2010-09-09'
Description: Windows EC2 Auto Scaling Group for PowerPoint Rendering Agent

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Pre-baked Windows AMI with PowerPoint and agent.py
  InstanceType:
    Type: String
    Default: t3.large
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  ClusterName:
    Type: String
  ScriptURL:
    Type: String 

Resources:
  EC2AgentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound RDP and inbound from cluster nodes
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref SecurityGroupId
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0

  RenderAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-RenderAgentRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: RenderAgentAppPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: "*"
              - Effect: Allow
                Action: 
                  - ec2:DescribeInstances
                Resource: "*"
              - Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"
              - Effect: Allow
                Action: 
                  - ssm:DescribeInstanceInformation
                  - ssm:GetCommandInvocation
                  - ssm:SendCommand
                  - ssm:StartSession
                Resource: "*"

  RenderAgentSSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: WindowsAgentSetupScript
      DocumentType: Command
      DocumentFormat: YAML
      TargetType: /AWS::EC2::Instance
      Content:
        schemaVersion: "2.2"
        description: "Powershell script to setup windows render agent."
        mainSteps:
          - action: aws:runPowershellScript
            name: downloadAndRunScript
            inputs:
              runCommand:
                - "Invoke-WebRequest -Uri '{{ScriptURL}}' -OutFile C:\\userdata-run.ps1"
                - "powershell.exe -ExecutionPolicy Bypass -File C:\\userdata-run.ps1 {{AWS::Region}} {{ClusterName}}"


  RenderAgentInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${AWS::StackName}-RenderAgentInstanceProfile"
      Path: /
      Roles:
        - !Ref RenderAgentRole
  RenderLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate   
    Properties:
      LaunchTemplateName: windows-render-agent-template
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            SubnetId: !Ref SubnetId
            Groups:
              - !Ref EC2AgentSecurityGroup
        IamInstanceProfile:
          Name: !Ref RenderAgentInstanceProfile
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100
              VolumeType: gp3
              DeleteOnTermination: true

  RenderAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref RenderLaunchTemplate
        Version: !GetAtt RenderLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      Tags:
        - Key: Name
          Value: windows-render-agent
          PropagateAtLaunch: true

Outputs:
  LaunchTemplateId:
    Value: !Ref RenderLaunchTemplate

  AutoScalingGroupName:
    Value: !Ref RenderAutoScalingGroup
